server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # deny access to sensitive files
    location ~* \.json$ {
        # allow config.json to be fetched by client; do not block
        try_files $uri =404;
    }

    location ~* \.md$ { return 404; }
}
